#!/usr/bin/env bash
set -euo pipefail

# Sync generated deployment-manifest copies from the single source of truth.
#
# Canonical (edit these):
#   deployments/<network>.json
#
# Auto-generated (do not edit by hand):
#   deployments/<network>.md
#
# Notes:
# - docs/deployments/<version>-<network>.md is generated by:
#     python3 scripts/sync_docs_deployments.py --write
#   and is intentionally NOT handled here, so that there is exactly one
#   canonical generator for docs/deployments.
# - Optional runtime/app deployment mirrors can be synced by a repo-local helper
#   when that helper exists.

MODE="write"
if [[ "${1:-}" == "--check" ]]; then
  MODE="check"
elif [[ "${1:-}" == "--write" || "${1:-}" == "" ]]; then
  MODE="write"
elif [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  cat <<USAGE
Usage:
  scripts/sync_deployments_all.sh            # write/sync all generated copies
  scripts/sync_deployments_all.sh --write    # same as default
  scripts/sync_deployments_all.sh --check    # CI mode; fails if drift exists

Notes:
  - Single source of truth: deployments/<network>.json
  - Write mode includes local.json when deployments/local.json exists
  - Check mode verifies repo-root markdown mirrors and any repo-local
    deployment-mirror helper when present
USAGE
  exit 0
else
  echo "Unknown argument: ${1}" >&2
  exit 2
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_DIR="${ROOT_DIR}/deployments"
RENDER_PY="${ROOT_DIR}/scripts/render_deployment_md.py"

find_optional_mirror_helper() {
  find "${ROOT_DIR}/scripts" -maxdepth 1 -type f -name 'sync_*deployments*.sh' ! -name 'sync_deployments_all.sh' | sort | head -n 1
}

OPTIONAL_MIRROR_HELPER="${DEPLOYMENT_MIRROR_HELPER:-}"
if [[ -z "${OPTIONAL_MIRROR_HELPER}" ]]; then
  OPTIONAL_MIRROR_HELPER="$(find_optional_mirror_helper || true)"
fi

if [[ ! -f "${RENDER_PY}" ]]; then
  echo "Missing renderer: ${RENDER_PY}" >&2
  exit 1
fi

# Discover canonical deployment manifests, including local.json when present.
mapfile -t JSON_FILES < <(find "${SRC_DIR}" -maxdepth 1 -type f -name '*.json' | sort)

if [[ ${#JSON_FILES[@]} -eq 0 ]]; then
  echo "No deployment manifests found in ${SRC_DIR} (*.json)" >&2
  exit 1
fi

write_one() {
  local json_path="$1"
  local network
  network="$(basename "${json_path}" .json)"

  # Human-readable mirror in repo root
  python3 "${RENDER_PY}" --json "${json_path}" --network "${network}" --format repo > "${SRC_DIR}/${network}.md"

  # docs/deployments is generated by scripts/sync_docs_deployments.py (separate, single source of truth)
}

check_repo_one() {
  local json_path="$1"
  local network
  network="$(basename "${json_path}" .json)"

  local repo_md="${SRC_DIR}/${network}.md"
  local exit_code=0

  if [[ ! -f "${repo_md}" ]]; then
    echo "Missing generated markdown mirror: ${repo_md}" >&2
    exit_code=1
  else
    local tmp_repo
    tmp_repo="$(mktemp)"
    chmod 600 "$tmp_repo"
    python3 "${RENDER_PY}" --json "${json_path}" --network "${network}" --format repo > "${tmp_repo}"

    if ! diff -u "${tmp_repo}" "${repo_md}" >/dev/null; then
      echo "Manifest drift detected (deployments JSON vs deployments markdown) for ${network}.md:" >&2
      diff -u "${tmp_repo}" "${repo_md}" >&2 || true
      exit_code=1
    fi
    rm -f "${tmp_repo}"
  fi

  return "${exit_code}"
}

if [[ "${MODE}" == "write" ]]; then
  for f in "${JSON_FILES[@]}"; do
    write_one "${f}"
  done

  if [[ -x "${OPTIONAL_MIRROR_HELPER}" ]]; then
    bash "${OPTIONAL_MIRROR_HELPER}" --write
  fi

  echo "[sync-deployments] Synced ${#JSON_FILES[@]} manifest(s) from deployments/*.json" >&2
  echo "[sync-deployments] Updated:" >&2
  echo "  - deployments/*.md" >&2
  if [[ -x "${OPTIONAL_MIRROR_HELPER}" ]]; then
    echo "  - repo-local deployment mirrors" >&2
  fi
  exit 0
fi

# MODE=check
exit_code=0
for f in "${JSON_FILES[@]}"; do
  if ! check_repo_one "${f}"; then
    exit_code=1
  fi
done

if [[ -x "${OPTIONAL_MIRROR_HELPER}" ]]; then
  if ! bash "${OPTIONAL_MIRROR_HELPER}" --check; then
    exit_code=1
  fi
fi

if [[ "${exit_code}" -ne 0 ]]; then
  echo "" >&2
  echo "Fix: run 'bash scripts/sync_deployments_all.sh' and commit the updated generated files." >&2
fi

exit "${exit_code}"
